version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - team-bjj-net

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - team-bjj-net

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - team-bjj-net

    node:
        image: node:18
        working_dir: /usr/src/app
        tty: true
        volumes:
            - .:/usr/src/app
        ports:
        - "3000:3000"
        networks:
            - team-bjj-net
        command: sh -c "npm install && npm run dev"

    # redis
    redis:
        image: redis:latest
        networks:
            - team-bjj-net

networks:
    team-bjj-net:
        driver: bridge
